### ISSUE TITLE
Usernames should be links 

### ISSUE THREAD

**Issue by onlyproevo** [paul999/mention#10]
For example: **[Paul9999](https://github.com/paul999)** rather than _Paul9999_

**Comment by Kaelko** [comment]
Still waiting release with this feature. Very useful and much needed function. Thanks for this great extension dev

**Comment by ftc2** [comment]
agreed, this would be great. very much needed feature.

**Comment by school-bus-driver** [comment]
> For example: **[Paul9999](https://github.com/paul999)** rather than _Paul9999_

I would really like to see this feature ASAP! 

Thank you vary much for your great work...

**Comment by school-bus-driver** [comment]
That's most important update that i need on the moment!

**Comment by ftc2** [comment]
paul is not interested in adding it to his extension. if you go on the phpbb community support forum for this extension, there's [one or two solutions posted by others](https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/203006) you can patch into it yourself. i did that for years without issue.

**Comment by school-bus-driver** [comment]
> meanwhile, i'm happily using discourse now and am enjoying this and other sane features just built into the core product. and new features coming in all the time at light speed from a responsive, passionate, **welcoming** dev community (with funding) who doesn't reject things for no reason. phpbb even with every sad, spaghetti code plugin under the sun will never reach feature parity with discourse ;)
> 
> but if you want this feature, you should just add it yourself. paul is not interested in adding it to his extension. if you go on the phpbb community support forum for this extension, there's [one or two solutions posted by others](https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/203006) you can patch into it yourself. i did that for years without issue.

i also did use the bbcode provided here 
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/203006?p=858361#p858361
but with the new update bbcode is gone - and I'm stuck, because i want to upgrade to 2.0.0 but my board members are alreay used to click on the username and it will be really difficult to lose it...

**Comment by ftc2** [comment]
> i also did use the bbcode provided here
> https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/203006?p=858361#p858361
> but with the new update bbcode is gone - and I'm stuck, because i want to upgrade to 2.0.0 but my board members are alreay used to click on the username and it will be really difficult to lose it...

ah, i see.

i'm not using phpbb anymore, but i could try to help you get it working. not sure how to proceed though, and this might be getting a little off topic considering it's a 'wont support' feature.

**Comment by ftc2** [comment]
@4388450 which version of phpBB are you on? probably doesn't matter, but if i have some time today, i'll load up a dev environment with this extension and try to come up with a new solution for you. just because.

btw i'm the one who posted the original solution.

**Comment by school-bus-driver** [comment]
> @4388450 which version of phpBB are you on? probably doesn't matter, but if i have some time today, i'll load up a dev environment with this extension and try to come up with a new solution for you. just because.
> 
> btw i'm the one who posted the original solution.

Thank you!

Im on the latest version

**Comment by ftc2** [comment]
ok, first of all, my compliments to paul. i am seeing some solid improvements to the extension since last time i looked at it (despite inexplicably not supporting this much-requested feature...lol)

obviously also big shoutouts to `s9e` / `JoshyPHP` – **the real MPV**. most relevant improvements to phpbb in recent memory are all thanks to him, and his work is what makes this fix so trivial.

@4388450 ok, i looked over it all, and here is my take on the situation.

my solution was functionally superior to the one you used (posted by `halil16`) because it incorporated uid into the bbcode. this means that the clickable reference should persist if a user's username changes. his solution references username directly. however, his solution was obviously easier to implement for the forum admin.

fortunately, paul now includes uid in his new bbcode, but it kind of doesn't matter because i don't think it's possible to modify his bbcode without modifying his extension.

btw, he changed from `mention` to `smention` bbcode name to maintain backwards compatibility with old posts i guess.

i think the roadblock you face stems from the bbcode not being published in the acp, and you can't just add it because his extension publishes the bbcode on top of a user's (via `$event['configurator']->BBCodes->addCustom()`).

the real solution is to migrate to discourse (can give you pointers) ;)

but ok, here's what to do:

replace this:
https://github.com/paul999/mention/blob/2.0.0/event/main_listener.php#L120-L127

with this:
```php
	public function configure_bbcode($event)
	{
		$configurator = $event['configurator'];
		$configurator->BBCodes->addCustom(
			'[smention u={NUMBER?} g={NUMBER?}]{TEXT}[/smention]',
			'<xsl:choose>
				<xsl:when test="@u">
					<a href="./memberlist.php?mode=viewprofile&u={@u}"><em class="mention">@{TEXT}</em></a>
				</xsl:when>
				<xsl:otherwise><em class="mention">@{TEXT}</em></xsl:otherwise>
			</xsl:choose>'
		);
	}
```

and ofc disable/enable the extension.

for reference: https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/

feel free to share this on the aforementioned phpbb topic if you want. 🤷‍♂️

**Comment by school-bus-driver** [comment]
> ok, first of all, my compliments to paul. i am seeing some solid improvements to the extension since last time i looked at it (despite inexplicably not supporting this much-requested feature...lol)
> 
> obviously also big shoutouts to `s9e` / `JoshyPHP` – **the real MPV**. most relevant improvements to phpbb in recent memory are all thanks to him, and his work is what makes this fix so trivial.
> 
> @4388450 ok, i looked over it all, and here is my take on the situation.
> 
> my solution was functionally superior to the one you used (posted by `halil16`) because it incorporated uid into the bbcode. this means that the clickable reference should persist if a user's username changes. his solution references username directly. however, his solution was obviously easier to implement for the forum admin.
> 
> fortunately, paul now includes uid in his new bbcode, but it kind of doesn't matter because i don't think it's possible to modify his bbcode without modifying his extension.
> 
> btw, he changed from `mention` to `smention` bbcode name to maintain backwards compatibility with old posts i guess.
> 
> i think the roadblock you face stems from the bbcode not being published in the acp, and you can't just add it because his extension publishes the bbcode on top of a user's (via `$event['configurator']->BBCodes->addCustom()`).
> 
> the real solution is to migrate to discourse (can give you pointers) ;)
> 
> but ok, here's what to do:
> 
> replace this: https://github.com/paul999/mention/blob/2.0.0/event/main_listener.php#L120-L127
> 
> with this:
> 
> ```
> 	public function configure_bbcode($event)
> 	{
> 		$configurator = $event['configurator'];
> 		$configurator->BBCodes->addCustom(
> 			'[smention u={NUMBER?} g={NUMBER?}]{TEXT}[/smention]',
> 			'<xsl:choose>
> 				<xsl:when test="@u">
> 					<a href="./memberlist.php?mode=viewprofile&u={@u}"><em class="mention">@{TEXT}</em></a>
> 				</xsl:when>
> 				<xsl:otherwise><em class="mention">@{TEXT}</em></xsl:otherwise>
> 			</xsl:choose>'
> 		);
> 	}
> ```
> 
> and ofc disable/enable the extension.
> 
> for reference: https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/
> 
> feel free to share this on the aforementioned phpbb topic if you want. 🤷‍♂️

@ftc2 Thanks a million!
It works like a charm...

One minor issue, when im hovering with the mouse only the underline turns red.
Usually the whole username needs to turn red like @admin in the image


![1](https://user-images.githubusercontent.com/67440797/233225980-26428476-eed6-4514-8909-57cc09b00112.gif)

**Comment by ftc2** [comment]
> One minor issue, when im hovering with the mouse only the underline turns red. Usually the whole username needs to turn red like @admin in the image

hm, idk. something is up with your css or something. or we're not on the same versions of phpbb or the extension.
here's how it looks with a fresh install of latest phpbb and the extension:

without hover:
<img width="178" alt="image" src="https://user-images.githubusercontent.com/9761890/233231241-e97c0473-d551-4e77-a059-6fd1c95d75f1.png">

with hover:
<img width="98" alt="image" src="https://user-images.githubusercontent.com/9761890/233231301-eb1730cd-58e3-46f2-ad67-45e97801a75a.png">

too bad github doesn't have a pm feature or i'd ask for your site's url to take a look.

@4388450 are you `Thank you` or whatever on there? i can pm you if you want.

**Comment by school-bus-driver** [comment]
> > One minor issue, when im hovering with the mouse only the underline turns red. Usually the whole username needs to turn red like @admin in the image
> 
> hm, idk. something is up with your css or something. or we're not on the same versions of phpbb or the extension. here's how it looks with a fresh install of latest phpbb and the extension:
> 
> without hover: <img alt="image" width="178" src="https://user-images.githubusercontent.com/9761890/233231241-e97c0473-d551-4e77-a059-6fd1c95d75f1.png">
> 
> with hover: <img alt="image" width="98" src="https://user-images.githubusercontent.com/9761890/233231301-eb1730cd-58e3-46f2-ad67-45e97801a75a.png">
> 
> too bad github doesn't have a pm feature or i'd ask for your site's url to take a look.
> 
> @4388450 are you `Thank you` or whatever on there? i can pm you if you want.

Yes, im Thank you

But i dont like it red so i changed in acp "post settings" the color to black

thats why its different, but still only the underline is a link the username is not a link

change the color in acp and you will find the same issue.

**Comment by school-bus-driver** [comment]
@ftc2 
Good morning, did you notice my issue?

**Comment by ftc2** [comment]
like i said, it depends on your site's css.

you could try adding the `mention` class to the link. like:

from:
```html
<a href="./memberlist.php?mode=viewprofile&u={@u}">
```

to:
```html
<a class="mention" href="./memberlist.php?mode=viewprofile&u={@u}">
```

**Comment by school-bus-driver** [comment]
> like i said, it depends on your site's css.
> 
> you could try adding the `mention` class to the link. like:
> 
> from:
> 
> ```
> <a href="./memberlist.php?mode=viewprofile&u={@u}">
> ```
> 
> to:
> 
> ```
> <a class="mention" href="./memberlist.php?mode=viewprofile&u={@u}">
> ```

Getting a HTTP ERROR 500 after applying it

**Comment by ftc2** [comment]
> Getting a HTTP ERROR 500 after applying it

you probably made a mistake in editing it.

try this:

```php
	public function configure_bbcode($event)
	{
		$configurator = $event['configurator'];
		$configurator->BBCodes->addCustom(
			'[smention u={NUMBER?} g={NUMBER?}]{TEXT}[/smention]',
			'<xsl:choose>
				<xsl:when test="@u">
					<a class="mention" href="./memberlist.php?mode=viewprofile&u={@u}"><em class="mention">@{TEXT}</em></a>
				</xsl:when>
				<xsl:otherwise><em class="mention">@{TEXT}</em></xsl:otherwise>
			</xsl:choose>'
		);
	}
```

**Comment by school-bus-driver** [comment]
> > Getting a HTTP ERROR 500 after applying it
> 
> you probably made a mistake in editing it.
> 
> try this:
> 
> ```
> 	public function configure_bbcode($event)
> 	{
> 		$configurator = $event['configurator'];
> 		$configurator->BBCodes->addCustom(
> 			'[smention u={NUMBER?} g={NUMBER?}]{TEXT}[/smention]',
> 			'<xsl:choose>
> 				<xsl:when test="@u">
> 					<a class="mention" href="./memberlist.php?mode=viewprofile&u={@u}"><em class="mention">@{TEXT}</em></a>
> 				</xsl:when>
> 				<xsl:otherwise><em class="mention">@{TEXT}</em></xsl:otherwise>
> 			</xsl:choose>'
> 		);
> 	}
> ```

Didn't fix it. but after i applied it with the code of @halil16 posted on phpbb it did work!
```

public function configure_bbcode($event)
	{
		$configurator = $event['configurator'];
		$configurator->BBCodes->addCustom(
			'[smention u={NUMBER?} g={NUMBER?}]{TEXT}[/smention]',
			'<xsl:choose>
				<xsl:when test="@u">
					<a href="./memberlist.php?mode=viewprofile&un={TEXT}" class="mention">@{TEXT}</a>
				</xsl:when>
				<xsl:otherwise><em class="mention">@{TEXT}</em></xsl:otherwise>
			</xsl:choose>'
		);
	}

```
makes sense?

**Comment by 4388450** [comment]
With your code i got this... 

![Screenshot 2023-04-20 172728](https://user-images.githubusercontent.com/67440797/233491934-6db446bb-6a65-48ca-8397-7f1d4f9bf0b7.png)

With his code i got this

![h](https://user-images.githubusercontent.com/67440797/233491979-f283db46-adef-49a9-8ce3-b3884398ac1a.png)

**Comment by ftc2** [comment]
idk, looking at your site would be more productive than playing guessing games with your css, lol

> too bad github doesn't have a pm feature or i'd ask for your site's url to take a look.
> @4388450 are you `Thank you` or whatever on there? i can pm you if you want.

**Comment by 4388450** [comment]
> idk, looking at your site would be more productive than playing guessing games with your css, lol
> 
> > too bad github doesn't have a pm feature or i'd ask for your site's url to take a look.
> > @4388450 are you `Thank you` or whatever on there? i can pm you if you want.

http://newvelt.42web.io/index.php

**Comment by school-bus-driver** [comment]
> > idk, looking at your site would be more productive than playing guessing games with your css, lol
> > > too bad github doesn't have a pm feature or i'd ask for your site's url to take a look.
> > > @4388450 are you `Thank you` or whatever on there? i can pm you if you want.
> 
> http://newvelt.42web.io/index.php
test account 
username: test
password: test123
> 
> you can pm me too @thank you

**Comment by ftc2** [comment]
got it, thanks. sorry, i've lost track of exactly what you want though. compared to how it is right now, what do you want different?

**Comment by school-bus-driver** [comment]
> got it, thanks. sorry, i've lost track of exactly what you want though. compared to how it is right now, what do you want different?

now only the underline is a link - not the username

**Comment by ftc2** [comment]
the whole thing is a link. maybe i'm misunderstanding. are you saying you want the underline to be a different color or something?

**Comment by school-bus-driver** [comment]
> the whole thing is a link. maybe i'm misunderstanding. are you saying you want the underline to be a different color or something?

![233225980-26428476-eed6-4514-8909-57cc09b00112](https://user-images.githubusercontent.com/67440797/233498381-38b668bc-a06c-425e-a97e-4bd70790e519.gif)

look at the gif, when im hovering on the admin username, both the username and underline are getting red

but when im hovering on user, only the underline gets red

**Comment by ftc2** [comment]
so you're saying you want the mention link (text and underline) to change from black to red when you hover?

**Comment by school-bus-driver** [comment]
> so you're saying you want the mention link to change from black to red when you hover?

yes like it used to be on the previous version with halil16 bbcode

check out this post
http://ivelt1.epizy.com/viewtopic.php?p=12#p12

**Comment by 4388450** [comment]
OK When i replace this line
`<a class="mention" href="./memberlist.php?mode=viewprofile&u={@u}"><em class="mention">@{TEXT}</em></a>`

With this line
`<a href="./memberlist.php?mode=viewprofile&un={TEXT}" class="mention">@{TEXT}</a>`

It works great!

Makes sense?

**Comment by paul999** [comment]
As said before, I won't be adding support for this, nor will I be providing support for this change. This is not the place to discuss this change, ans closing it as such.
