### ISSUE TITLE
Special letters in usernames

### ISSUE THREAD

**Issue by kumencz** [paul999/mention#16]
Special letters in usernames destroying search when they are typed.

**Example:**
@stono - generate drop down menu with usernames: "@stonožka" and "@stonohavic" usernames
When another letter was entered:
@stonož - drop down menu is gone

**Comment by jbreu** [comment]
I second this, in my case especially for white spaces. In my forum all people have to use their real names. There are many people with same first names, which is a problem due to this bug

**Comment by Stono** [comment]
Just love being tagged in something that's nothing to do with me :D
