### ISSUE TITLE
Fatal error: Cannot use object of type phpbb\user as array in /homepages/21/d511922987/htdocs/foro/ext/paul999/mention/event/main_listener.php on line 263

### ISSUE THREAD

**Issue by uruguayito** [paul999/mention#17]
After press  send button to leave a message appears this error

any idea?

**Comment by paul999** [comment]
What version of the extension are you using?

**Comment by uruguayito** [comment]
1.0.0-RC1

**Comment by paul999** [comment]
Thats impossible, because that file has just 227 lines in RC1 https://github.com/paul999/mention/blob/1.0.0-RC1/event/main_listener.php

**Comment by uruguayito** [comment]
http://imgur.com/a/q8Grx

**Comment by paul999** [comment]
That doesn't  say much, as I didn't update the version in GIT. How did you download it. And when?

**Comment by paul999** [comment]
Please also test it with this download: https://github.com/paul999/mention/archive/master.zip

**Comment by uruguayito** [comment]
I just downloaded this version..... but same error: 
Fatal error: Cannot use object of type phpbb\user as array in /homepages/21/d511922987/htdocs/foro/ext/paul999/mention/event/main_listener.php on line 263

**Comment by uruguayito** [comment]
http://imgur.com/a/3wd9g
