### ISSUE TITLE
Redirects to this after using Mentions, on either QuickReply or Full Editor.

### ISSUE THREAD

**Issue by spiritatbay** [paul999/mention#18]
[phpBB Debug] PHP Notice: in file [ROOT]/phpbb/auth/auth.php on line 424: Undefined index: user_type
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1835: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)

It posts fine, just gives that error message in a blank page each time a Mention is used.

**Comment by paul999** [comment]
What version are you using?

**Comment by spiritatbay** [comment]
1.0.0-RC1
phBB 3.2.0, php 7.0

Jorge E Castillo
Sent with Spark

**Comment by paul999** [comment]
Does this still happen with this download: https://github.com/paul999/mention/archive/master.zip ?

**Comment by spiritatbay** [comment]
Apologies for the long delay in reply. I had gone away to China for a month and just got back this weekend. 

1.0.1 fixed the issue, but the names no longer appear italicized when mentioned.

**Comment by paul999** [comment]
Yes, that is by design.
