### ISSUE TITLE
You can't use BBCodes [mention]

### ISSUE THREAD

**Issue by uruguayito** [paul999/mention#21]
after this, https://github.com/paul999/mention/commit/7ba4d13c02627a96881d2acab6a0dc6c6fa3071b, now this error:

You can't use BBCodes [mention] .....

Permissions set correctly

**Comment by paul999** [comment]
Keep in mind that this is a development version, and should not be used. Issues will happen, and in general you should not report issues from the development release. Only the released versions are supported.
