### ISSUE TITLE
Simple mentions issues

### ISSUE THREAD

**Issue by nikolaleon** [paul999/mention#25]
Notifications tends to be duplicated

1. When I enter username with numbers it gives whole listing, does not target said name: http://image.prntscr.com/image/e23e5a812bd94a9abfd63bb6695a460d.png

2. On a 3gb+ board enabling extension tends to hang and mysql usage is at top resulting in a crash.

2. Upon enalbing ext and applying permissions following error appears: http://prnt.sc/f202a0 and recent one: http://prntscr.com/f204dj

3.Upon uploading ext: it gives 2 versions, older one @mentions and phpbb mentions using new one

- Greying out parts because images are on a public place. Thanks

**Comment by paul999** [comment]
Please create seperate issues for each issue.
