### ISSUE TITLE
Display name should match the extension name ;)

### ISSUE THREAD

**Issue by VSEphpbb** [paul999/mention#27]
The ext is titled "Simple mentions" but in composer.json the display name is "phpBB mentions" (I also noticed phpBB mentions is the name in the code docblocks).

This is a little inconsistent. In an board with tons of extensions, it's hard to find since you go looking for Simple mentions but don't find it since it's actually displayed as phpBB mentions.

**Comment by paul999** [comment]
Argh... :/
