### ISSUE TITLE
Feature: Provide a way to change the color of the mention

### ISSUE THREAD

**Issue by VSEphpbb** [paul999/mention#30]
Mentioned names are hardcoded to #ff0000.

It would be good to be able to change that maybe, via ACP or something. As some styles might not look good with that color, or some user's may just want a more subtle appearance (like not changing the font color from the rest of the text, and just keeping it bold).

**Comment by paul999** [comment]
Yeah, it comes from being simple :)

**Comment by MichaIng** [comment]
@paul999 
And how to change the colour now? I can't find some settings neither in ACP nor UCP.
