### ISSUE TITLE
Mentions issue 1 Does not target username

### ISSUE THREAD

**Issue by nikolaleon** [paul999/mention#31]
When I enter username with numbers it gives whole listing, does not target said name: http://image.prntscr.com/image/e23e5a812bd94a9abfd63bb6695a460d.png

**Comment by secretmyth** [comment]
I have the same issue on my forum.
I thing issue is here : https://github.com/paul999/mention/blob/master/styles/all/template/js/mention.js
It can not parse Char other than alphabet's [Non Case Sensitive] ,
Illustration of Bug :
1. It can take @aac but Not @aa2 ,
Can take @aac ; [b]aac[/b]a20  gets parsed. :
[url=https://postimg.org/image/v82d6qv77/][img]https://s5.postimg.org/v82d6qv7b/R-_APKbug2.png[/img][/url]
But Not @aa2 ; [b]AA2[/b]001 does not gets parsed Instead stays on [b]AA[/b]2001. :
[url=https://postimg.org/image/t4rxz2veb/][img]https://s5.postimg.org/ysy8pyzqv/R-_APKbug1.png[/img][/url]
2. Can not take all UniCode Char Eg= "❶" :
[url=https://postimg.org/image/m2u0cvrsj/][img]https://s5.postimg.org/dkkk8jl9z/R-_APKbug3.png[/img][/url]

**Comment by dark-1** [comment]
I Second This.

**Comment by dark-1** [comment]
@secretmyth ,

Kindly remove BBcode's , for   
`[b]aac[/b]a20 gets parsed.   `
&    
`[b]AA2[/b]001 does not gets parsed Instead stays on [b]AA[/b]2001.   `

Instead Use :   
`Can take @aac ; **aac**a20 gets parsed. :    `
&     
`But Not @aa2 ; **AA2**001 does not gets parsed Instead stays on **AA**2001. :    `

**Comment by paul999** [comment]
This should be fixed by https://github.com/paul999/mention/pull/64
