### ISSUE TITLE
Error while quoting posts

### ISSUE THREAD

**Issue by maras26** [paul999/mention#35]
`[phpBB Debug] PHP Notice: in file [ROOT]/ext/paul999/mention/event/main_listener.php on line 287: Undefined index: message
[phpBB Debug] PHP Notice: in file [ROOT]/ext/paul999/mention/event/main_listener.php on line 290: Indirect modification of overloaded element of phpbb/event/data has no effect
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)`

Simple mention v. RC2

**Comment by paul999** [comment]
What php version are you using?

**Comment by maras26** [comment]
php 7
