### ISSUE TITLE
When using '@' and a real username but not using [mention] we have a permanent dropdown with the username in following quotes of that post

### ISSUE THREAD

**Issue by plagoa** [paul999/mention#40]
While testing the extension in my board I noticed that if I try to  tag someone but end up not really tagging them, ending up with only the text "@username" (and not `[mention]username[/mention]` )  whenever someone quotes that post then a dropdown with the username will always be visible and will follow the cursor position as if to finish tagging the user on the quoted post.

Sample:

I'm quoting a post with the text: "test @admin." (not a mention). A dropdown trying to complete the mention is displayed:

![simple_mentions_1](https://cloud.githubusercontent.com/assets/7498785/26245163/c84eb52e-3c8a-11e7-860e-f6984949f3d9.png)

The dropdown follows the cursor:

![simple_mentions_2](https://cloud.githubusercontent.com/assets/7498785/26245168/ca06b5c4-3c8a-11e7-89a6-256af9c667ec.png)

if I press enter, then the tag `[mention]admin[/mention]` will be added, which is annoying.

Also, this happens in any quote of that message, even if there are multiple quotes in the middle:

![simple_mentions_3](https://cloud.githubusercontent.com/assets/7498785/26245370/afa60814-3c8b-11e7-857b-6c2c389bd39f.png)

**Comment by paul999** [comment]
This is fixed by https://github.com/paul999/mention/pull/64
