### ISSUE TITLE
Popup not showing when single @ already exists in the text

### ISSUE THREAD

**Issue by plagoa** [paul999/mention#50]
if there's an @ in the text followed by a space, subsequent @mentions will not work:

Example:

1- Lorem ipsum some text @user--> dropdown shows for all nicknames that start with ('user')
2- Lorem ipsum '@' some text @user --> dropdown shows correctly
3- Lorem ipsum @ some text @user --> no dropdown shows at all

What's happening is that in the last case the extension will keep trying to find users for the first @ as you can see in the image below:

![capture](https://user-images.githubusercontent.com/7498785/30672577-2449e18c-9e65-11e7-8328-9aea4b66eb9e.PNG)

Probably the extension should ignore @ when there's nothing directly after it (ie, is followed by a blank space).

**Comment by Mickroz** [comment]
I would like to mention that when using only @ all text after it will get the mention color.

**Comment by paul999** [comment]
This is fixed by https://github.com/paul999/mention/pull/64
