### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by bcurran3** [paul999/mention#51]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "". in /home/xxxxxx/public_html/vendor/symfony/dependency-injection/ContainerBuilder.php:824 Stack trace: #0 /home/xxxxxx/public_html/vendor/symfony/dependency-injection/ContainerBuilder.php(464): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('') #1 /home/xxxxxx/public_html/phpbb/notification/manager.php(881): Symfony\Component\DependencyInjection\ContainerBuilder->get('') #2 /home/xxxxxx/public_html/phpbb/notification/manager.php(870): phpbb\notification\manager->load_object('') #3 /home/xxxxxx/public_html/phpbb/notification/manager.php(370): phpbb\notification\manager->get_method_class('') #4 /home/xxxxxx/public_html/phpbb/notification/manager.php(295): phpbb\notification\manager->add_notifications_for_users('notification.ty...', Array, Array) #5 /home/xxxxxx/public_html/phpbb/notification/manager.php(266): phpbb\notification\manager->add_notifications('notific in /home/xxxxxx/public_html/vendor/symfony/dependency-injection/ContainerBuilder.php on line 824

-------------------

I get the above error randomly (so called because I'm sure there is a rhyme and reason that I just haven't noticed yet.) when saving a message. Not 100% sure, but seems to be related to the mention extension.  Has been happening with 1.01 and 1.02. PHPbb is 3.2.0 previously and 3.2.1 now. PHP is 7.0. Ironically even though it errors out, the post gets saved (and everyone reposts making a duplicate).

**Comment by paul999** [comment]
This doesn't seem to be related to this extension. Please ask for support at phpBB.com.
