### ISSUE TITLE
Error in the url sent by email

### ISSUE THREAD

**Issue by barnabebear** [paul999/mention#53]
Hi Paul, 

just installed your extension which is great ! And thank you for this

Just one thing you might want to know, when I asked for a notification by email, the link that was in there was wrong, a “/” was missing just before viewtopic and after the name of my forum

So I received this

“Hello,
You just have been mentioned by "XXX" at "forumxxx".
To view the post you have been mentioned in use this link:
http://www.forumxxx.frviewtopic.php?p=135611#p135611 »

The link above is wrong, it should read instead: 
http://www.forumxxx.fr/viewtopic.php?p=135611#p135611

A small "/" make all the difference !

If you could fix it that would be so terrific.

Anyways, thanks again for his incredbly useful feature,
B

**Comment by paul999** [comment]
Please make sure to use the latest release from phpBB.com. This has already been fixed. Also, please keep in mind that this is not a support forum.
