### ISSUE TITLE
dropdown list does not show up

### ISSUE THREAD

**Issue by Puchahawa** [paul999/mention#6]
After the extension is activated I checked the permissions.  admins and registered members are yes for mentions.  checked my personal account and it was yes as well.

Went to post a message and attempted to mention my test account.  Typed @ran   and the dropdown did not appear.  Tried @ ran also with no success.  Could my issue be that there are only two members on my board?

Running 3.2.0  php 5.5.12 on apache 2.4.9  wampserver

**Comment by paul999** [comment]
Please post for support in the topic at phpbb.com
