### ISSUE TITLE
Fatal error: Cannot use object of type phpbb\user as array 

### ISSUE THREAD

**Issue by am2605** [paul999/mention#7]
I am seeing an error when I make a post, which I think is caused by the fix for #3 .  The error is:

PHP Fatal error:  Cannot use object of type phpbb\user as array in <path_to_my_board>\ext\paul999\mention\event\main_listener.php on line 181

I was able to fix this by changing 181 to:

`$on_page = $this->viewonline_helper->get_user_page($this->user->data['session_page']);`

And 183 to:

`if (0 === strpos($on_page,'posting'))`

phpBB version is 3.2.20
PHP Version: 5.6.6

EDIT: The above is not logically correct on a second look, so I'm not sure my solution is correct

**Comment by paul999** [comment]
You should not use a development version

**Comment by am2605** [comment]
Ooops, thanks.  I didn't see there was a release there, and I just grabbed the code from master.  Cheers

**Comment by paul999** [comment]
It was still a issue, so it needs to be fixed ;).
