### ISSUE TITLE
INCLUDECSS and so on should contain T_ASSETS_VERSION

### ISSUE THREAD

**Issue by ser** [paul999/mention#72]
because of caching,
```
<!-- INCLUDECSS @paul999_mention/tribute.css -->
```
should IMHO be extended by:
```
<!-- INCLUDECSS @paul999_mention/tribute.css?assets_version={T_ASSETS_VERSION} -->
```
and so other similar files as well

**Comment by paul999** [comment]
No, this is done automaticlly by INCLUDECSS already: https://github.com/phpbb/phpbb/blob/805b52a2ef1621574522a7906eaec0be16e1eb73/phpBB/phpbb/template/twig/node/includeasset.php#L52 :)
