### ISSUE TITLE
strange behaviour with soft links in filesystem

### ISSUE THREAD

**Issue by ser** [paul999/mention#73]
Hi, I noticed that I am unable to ```ln -s``` the extension from other part of filesystem to the phpbb installation, as mention in some magic way connects itself to the real place in filesystem and gives errors it cannot find files in expected locations.

Is it possible to make it agnostic to that issue?

**Comment by paul999** [comment]
Please provide the actual errors you are getting.

**Comment by ser** [comment]
It is easy to reproduce, but currently I am less sure it is related to your extension, as I noticed it with another one as well. So it might be a phbBB issue or it is related to my particular deployment.

I have my phpBB installed in ```/phpbb``` directory and it is served from ```https://my.server/phpbb/``` URI.
```
mkdir -p /opt/phpbb/ext/paul999
mv /phpbb/ext/paul999/mention /opt/phpbb/ext/paul999
ln -s /opt/phpbb/ext/paul999/mention /phpbb/ext/paul999
```
and after cleaning cache, links to css files from your extensions include ```https://my.server/opt/phpbb/ext/paul999/....``` instead of ```https://my.server/phpbb/ext/paul999/....``` and obviously files are not being found on that URI.

**Comment by paul999** [comment]
That is not an issue from this extension, but from phpBB itself. Also, to be honest, I don't think it is suggested to use symlinks to include extensions.
