### ISSUE TITLE
[Compatibility] Does not work in conjunction with senky/phpbb-ext-simplewysiwyg

### ISSUE THREAD

**Issue by ZoriaRPG** [paul999/mention#74]
Many forums try to adopt a WYSIWYG editor view, and it seems that the only one available for the current phpBB is https://github.com/senky/phpbb-ext-simplewysiwyg .

Sadly, the mention plugin does not work--at all--once the simplewysiwyg  is installed. IDK if you can suggest a WYSIWYG editor that *does* work, but you may want to commune with senky to try to make both of these work in unison.

**Comment by paul999** [comment]
Sorry, I have no plans to support other extensions.
