### ISSUE TITLE
Extension Outright Fails [phpBB 3.3.0]

### ISSUE THREAD

**Issue by ZoriaRPG** [paul999/mention#75]
It appears that, even *without* other extensions, the mention plugin does not work with phoBB 3.3.0, using our server config. Either this is a php issue , or some fault with 3.3.0 compatibility.

Server details:

Database server: | MySQL(i) 5.7.29-0ubuntu0.18.04.1
-- | --
GZip compression: | Off
PHP version: | 7.2.24-0ubuntu0.18.04.3
Orphan attachments: | 2
Board version: | 3.3.0 [ Re-Check version ]

Running on Ubuntu Server 18.04LTS, with NGINX. 

Forum URL: https:/openzc.org/forums

Report cc'd on the phpBB.org support forum plugin topic. I'm not yet familiar-enough with version differences between 3.3.0 and 3.2.x to know anything more specific.

**Comment by paul999** [comment]
Please post support questions at https://www.phpbb.com/customise/db/extension/simple_mentions/support

**Comment by ZoriaRPG** [comment]
> Please post support questions at https://www.phpbb.com/customise/db/extension/simple_mentions/support

We did. It's awaiting mod approval. We've only recently migrated to phpBB, so our account is sparkling new.

**Comment by paul999** [comment]
just tested it on a clean install, and seems to work properly. Please continue in the forums and provide the required information there.

**Comment by ZoriaRPG** [comment]
I solved this. The issue was with the local site config. 

In the local site config

`/etc/nginx/sites-available/openzc.org` 

I had this:

``` location /app.php { try_files $uri $uri/ /forum/app.php?$query_st$
        }
``

I had missed the absolute path to app.php in the above. 

Changing it as follows was what I needed to do

``` location /forum/app.php { try_files $uri $uri/ /forum/app.php?$query_st$
        }
```
