### ISSUE TITLE
[Feat] Set Colour Properties of Menu

### ISSUE THREAD

**Issue by ZoriaRPG** [paul999/mention#82]
Looks that the menu style is derived from tribute.css, not mention.css. I'm unsure what mention.css is doing yet. 

It'd be nice to have a config in the config file, or via a UI of some sort) to set the font properties, menu colour, and text colour for the menu, plus highlight colours, so that they are always *readable*. Dropdown menu width, and character point size, are also useful. (I have no clue what this looks like on higher resolutions, as I have no way to est that.)

If you can direct me at where this is governed (menu generation) I may come up with a user-friendly way to update it.  I would have expected those style sets to be what to edit, but I'm seemingly wrong. 

At the worst, perhaps a config like for the theme .css used by the plugin would work.

I added fields to tribute.css for defining user styles for our own use.

**Comment by paul999** [comment]
As with most extensions you will need to modify the CSS file for your specific style. I won't add configuration options for that.

**Comment by ZoriaRPG** [comment]
You should probably set the default values to `inherit` at the least. phojBB supports per-ext GUI config as well. It may not be too trying to add that in, but if you are *unwilling* to support it if I do, then I'd be wasting my time.

**Comment by paul999** [comment]
I haven't seen an extension that has support for modifying style changes in the ACP. And I have seen quiet a few extensions. As said, you can modify the CSS needed for your specific style, just move the css to the style directory and phpBB will reconise.
